---
title: "Horror movies analysis"
author: "Tamas Nagy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)

theme_set(theme_light())
library(easystats)

```

# Read horror movies dataset

```{r}
horror_movies_raw <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-11-01/horror_movies.csv')

horror_movies <- 
  horror_movies_raw %>% 
  mutate(runtime = na_if(runtime, 0),
         budget = na_if(budget, 0),
         revenue = na_if(revenue, 0),
         vote_average = na_if(vote_average, 0),
         popularity = na_if(popularity, 0),
         part_of_collection = !is.na(collection),
         budget = budget / 1e6,
         revenue = revenue / 1e6)


horror_movies
glimpse(horror_movies)

```

```{r}
horror_movies %>% 
  count(year = year(release_date)) %>% 
  ggplot() +
  aes(x = year, y = n) +
  geom_col()

horror_movies %>% 
  count(decade = year(release_date)%/%10*10) %>% 
  ggplot() +
  aes(x = decade, y = n) +
  geom_col()

```

# Runtime 

```{r}
horror_movies %>% 
  ggplot(aes(x = runtime)) +
  geom_histogram() +
  scale_x_log10()
  

horror_movies %>% 
  slice_max(runtime, n = 20) %>% 
  mutate(title = fct_reorder(title, runtime)) %>% 
  ggplot() +
  aes(x = runtime, y = title) +
  geom_col() +
  labs(title = "Longest horror movies", y = NULL)

```

# Budget
```{r}
qplot(horror_movies$budget) + scale_x_log10()
qplot(horror_movies$revenue) + scale_x_log10()

horror_movies %>% 
  drop_na(revenue)


```

# Votes
```{r}
qplot(horror_movies$vote_count) + scale_x_log10()
qplot(horror_movies$vote_average)
qplot(horror_movies$popularity) + scale_x_log10()

horror_movies %>% 
  filter(vote_count >= 100) %>% 
  ggplot() +
  aes(x = vote_average) +
  geom_histogram() +
  coord_cartesian(xlim = c(1,10))

summary(horror_movies$vote_average)

horror_movies %>% 
  ggplot() +
  aes(x = vote_count, y = popularity) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth()


horror_movies %>% 
  ggplot() +
  aes(x = vote_average, y = popularity) +
  geom_point() +
  scale_y_log10() +
  geom_smooth()
```

# Collection
```{r}
horror_movies %>% 
  count(part_of_collection)

horror_movies %>% 
  drop_na(collection_name) %>% 
  count(collection_name, original_language,  sort = TRUE)


horror_movies %>% 
  drop_na(collection_name) %>% 
  count(collection_name, original_language,  sort = TRUE) %>% 
  slice(1:15) %>% 
  mutate(collection_name = fct_reorder(collection_name, n)) %>% 
  ggplot() +
  aes(x = n, y = collection_name) +
  geom_col() +
  labs(y = NULL, title = "Collections with most films")
```

```{r}

library(widyr)

horror_movies %>% 
  separate_rows(genre_names, sep = ", ") %>% 
  filter(genre_names != "Horror") %>% 
  pairwise_count(genre_names, id) %>% 
  ggplot() +
  aes(x = item1, y = item2, fill = log10(n)) +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = NULL, y = NULL,
       title = "Co-occurence of movie genres in horror movies",
       fill = "Occurences (log10)")

```

# Modeling

```{r}

model_df <-
  horror_movies %>% 
  filter(vote_count >= 50) %>% 
  drop_na(revenue, budget, vote_average)

revenue_model <- 
  lm(log(revenue) ~ vote_average + budget + part_of_collection, 
   data = model_df) 

summary(revenue_model)

parameters(revenue_model, standardize = "refit")

check_model(revenue_model)

```

